# MountX Game List
# Format: package_name:mode
# mode: pkg   = mount entire Android/data/PKG folder
# mode: files = mount only Android/data/PKG/files subfolder
#
# Lines starting with '#' are treated as comments and are ignored.
# Blank lines are also ignored.
#
# Examples:
com.kurogame.wutheringwaves.global:pkg
com.HoYoverse.hkrpgoversea:files